apiVersion: v1
kind: Secret
metadata:
  name: hetch-secrets
type: Opaque
data:
  mongo_root_name: bW9uZ29fdXNlcgo=
  mongo_root_password: bW9uZ29fcGFzc3dvcmQK

# Persitant Volmes setup
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hetch-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hetch-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

# Microservices Setup
# Hetch-Translator Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hetch-translator
  labels:
    app: hetch-translator
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hetch-translator
  template:
    metadata:
      labels:
        app: hetch-translator
    spec:
      containers:
        - name: hetch-translator
          image: hetchfundcapital_hetch_translator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hetch-translator-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: hetch-translator
  type: LoadBalancer
